### ISSUE TITLE
it doesn't work when try it on another computer on same local network

### ISSUE THREAD

**Issue by amrkamal2025** [adolfintel/voicechat#1]
i try this project on my laptop and it works fine and i can hear my self but the problem when i put it on another computer on same local network and i change the ips and it doesn't work ?

**Comment by amrkamal2025** [comment]
i try this project on my laptop and it works fine and i can hear my self but the problem when i put it on another computer on same local network and i change the ips and it doesn't work ?

**Comment by adolfintel** [comment]
I made this thing many years ago, but let's try some troubleshooting.
-What happens when you try to connect to the server? Do you get a connection error?
If not,
-Does the mic level move?

**Comment by amrkamal2025** [comment]
Thanks for your replay and sorry for late .
There is no error when connecting but on the my second laptop  when i use the program yes the mic doesn't move 
but it works in general i test it from windows
any solution for that please ?

**Comment by adolfintel** [comment]
If the mic doesn't move, increase the volume, and make sure that the mic is the default input device in your system mixer. On GNU/Linux, it's alsamixer.

**Comment by adolfintel** [comment]
I assume the issue is resolved?
